name: salesbets_skeleton
description: Minimal Flutter skeleton for SalesBets assignment.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  cloud_firestore: ^4.9.0
  firebase_auth: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
