// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhdOMRobzgl9R546Y5ZR8idobQg3UNr5E',
    appId: '1:926788323063:web:75bbc95600de45d7f1b5f2',
    messagingSenderId: '926788323063',
    projectId: 'salesbate',
    authDomain: 'salesbate.firebaseapp.com',
    storageBucket: 'salesbate.firebasestorage.app',
    measurementId: 'G-FW2GVSLWX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRASGpyThfGnEb--xUEqXUpNayKb8dcU',
    appId: '1:926788323063:android:381a323c1ff54a54f1b5f2',
    messagingSenderId: '926788323063',
    projectId: 'salesbate',
    storageBucket: 'salesbate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ikkHmrvunfdwHw6g8prjYEd81_1dzbU',
    appId: '1:926788323063:ios:600b83041ec9af36f1b5f2',
    messagingSenderId: '926788323063',
    projectId: 'salesbate',
    storageBucket: 'salesbate.firebasestorage.app',
    iosBundleId: 'com.example.salesbetProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ikkHmrvunfdwHw6g8prjYEd81_1dzbU',
    appId: '1:926788323063:ios:600b83041ec9af36f1b5f2',
    messagingSenderId: '926788323063',
    projectId: 'salesbate',
    storageBucket: 'salesbate.firebasestorage.app',
    iosBundleId: 'com.example.salesbetProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhdOMRobzgl9R546Y5ZR8idobQg3UNr5E',
    appId: '1:926788323063:web:5b57719bbb990896f1b5f2',
    messagingSenderId: '926788323063',
    projectId: 'salesbate',
    authDomain: 'salesbate.firebaseapp.com',
    storageBucket: 'salesbate.firebasestorage.app',
    measurementId: 'G-TGQCM5MCHB',
  );
}
